### ISSUE TITLE
Optional Pointers are not supported

### ISSUE THREAD

**Issue by jamesmunns** [jamesmunns/optional_c#1]
You cant create pointer Optionals, like `Optional(type*)`. This means you cannot have non-nullable pointers

**Comment by jack126guy** [comment]
You also can't create Optionals for types like `struct example` or `enum status`.

**Comment by jamesmunns** [comment]
True, though you should be able to typedef these (this is what I normally do).

`typedef struct { ... } myStructType;` => `DefineOptional(myStructType)` => `Optional(myStructType) foo;`

**Comment by jamesmunns** [comment]
I fixed this by adding `DefineNamedOptional(struct foo, foo);`, which then lets you use `Optional(foo)` as normal. It also works with enums, unions, and even pointers.

For pointers you will need to define a name without a `*`, such as `DefineNamedOptional(float*, float_ptr);` => `Optional(float_ptr)`.

**Comment by jamesmunns** [comment]
Closing this issue. Fixed by `DefineNamedOptional()`
